# serverless.yml

service: serverless-python

plugins:
  - serverless-pseudo-parameters
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: src.web.handler.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    slimPatterns:
      - '**/*.egg-info*'
    noDeploy:
      - pytest

provider:
  name: aws
  runtime: python3.7
  region: eu-west-1
  memorySize: 256
  timeout: 10
  logRetentionInDays: 7

functions:
  web:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  cron:
    handler: src.cron.handler.run
    events:
      - schedule: rate(1 hour)
  worker:
    handler: src.worker.handler.run
    events:
      - sqs: arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:serverless-python-dev-queue

resources:
  Resources:
    Queue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "serverless-python-dev-queue"